In [1]:
import sympy as sy
import numpy as np

P0 = [1, 0.5]
P1 = [2, -1.5]
P2 = [3, 3.5]
P3 = [4, -9]

lamda0 = [[2],[1]] #Startvektor
Pges = [P0, P1, P2, P3] #Alle Punkte eintragen
tolerance = 0.0000000000002
def f(x, l1, l2):
    return sy.sin(l1*x) * sy.exp(l2*x)



i = 0
lTuple = sy.symbols('l(0:len(Pges))')
x = sy.symbols('x')
while (True):
    fLambda = np.empty([len(Pges), 1])
    for j in range(0,len(Pges)):
        try: 
            fLambda[j][0]
            fLambda[j][0] = Pges[j][1] - f(Pges[j][0], lamda0[0][0], lamda0[1][0]).evalf()
        except AttributeError: 
            fLambda[j][0] = Pges[j][1] - f(Pges[j][0], lamda0[0][0], lamda0[1][0])

    jacobi = np.empty([len(Pges), 2])
    for j in range(0,len(Pges)):
        f_l1 = sy.diff(f(Pges[j][0], lTuple[0], lTuple[1]), lTuple[0])
        f_l2 = sy.diff(f(Pges[j][0], lTuple[0], lTuple[1]), lTuple[1])
        try: 
            jacobi[j][0] = f_l1.subs([(lTuple[0], lamda0[0][0]), (lTuple[1], lamda0[1][0])]).evalf()
            jacobi[j][1] = f_l2.subs([(lTuple[0], lamda0[0][0]), (lTuple[1], lamda0[1][0])]).evalf()
        except AttributeError: 
            jacobi[j][0] = f_l1.subs([(lTuple[0], lamda0[0][0]), (lTuple[1], lamda0[1][0])])
            jacobi[j][1] = f_l2.subs([(lTuple[0], lamda0[0][0]), (lTuple[1], lamda0[1][0])])

    if(np.linalg.norm(np.matmul(np.transpose(jacobi), fLambda)) < tolerance):
        raise ValueError("Genauigkeit erreicht")
    else:
        jacobiT = np.transpose(jacobi)
        d = np.matmul(np.matmul(np.linalg.inv(np.matmul(jacobiT, jacobi)), jacobiT), fLambda)
        lamda0 = lamda0 + d
        i+= 1
        print("\u03BB %d: \n" %i, lamda0)


λ 1: 
 [[2.07004347]
 [0.71808418]]
λ 2: 
 [[2.2024458 ]
 [0.38761424]]
λ 3: 
 [[ 2.65382899]
 [-0.03641681]]
λ 4: 
 [[4.57485718]
 [1.55242645]]
λ 5: 
 [[4.53655833]
 [1.24850588]]
λ 6: 
 [[4.49537763]
 [0.97304224]]
λ 7: 
 [[4.46063164]
 [0.7519599 ]]
λ 8: 
 [[4.44584944]
 [0.61846802]]
λ 9: 
 [[4.4494496 ]
 [0.57518619]]
λ 10: 
 [[4.45150635]
 [0.5705234 ]]
λ 11: 
 [[4.45140195]
 [0.57026185]]
λ 12: 
 [[4.45142493]
 [0.57026634]]
λ 13: 
 [[4.45142154]
 [0.57026459]]
λ 14: 
 [[4.45142208]
 [0.57026483]]
λ 15: 
 [[4.45142199]
 [0.5702648 ]]
λ 16: 
 [[4.45142201]
 [0.5702648 ]]
λ 17: 
 [[4.45142201]
 [0.5702648 ]]
λ 18: 
 [[4.45142201]
 [0.5702648 ]]
λ 19: 
 [[4.45142201]
 [0.5702648 ]]
λ 20: 
 [[4.45142201]
 [0.5702648 ]]
λ 21: 
 [[4.45142201]
 [0.5702648 ]]
λ 22: 
 [[4.45142201]
 [0.5702648 ]]
λ 23: 
 [[4.45142201]
 [0.5702648 ]]
λ 24: 
 [[4.45142201]
 [0.5702648 ]]
λ 25: 
 [[4.45142201]
 [0.5702648 ]]


ValueError: Genauigkeit erreicht