In [2]:
import numpy as np

a=[[0,4,9],[5,2,3],[-8,0,-3]]

def frob(a,i):
    n=len(a) #len ist die Länge von a/Dimension
    f=np.eye(n) #einheitsmatrix mit n Zeilen
    for k in range(i+1,n): #k zwischen i und n
        f[k][i]=-a[k][i]/a[i][i]
    return f

l=np.zeros((len(a),len(a)))
p=np.eye(len(a))
pi=np.eye(len(a))
temp=np.eye(len(a))
for i in range(0,len(a)-1):
    pivot=i
    p=np.eye(len(a))
    for k in range(i+1,len(a)):
        if abs(a[pivot][i])<abs(a[k][i]):
            pivot=k
    temp[0]=p[i]
    p[i]=p[pivot]
    p[pivot]=temp[0]
    a=np.dot(p,a)
    pi=np.dot(p,pi)
    l=l+frob(a,i)
    if i>0:
        print("l",i+1,"=\n",p)
    a=np.dot(frob(a,i),a)
print("p:\n",pi)
print("R:\n",a)
print("Vorzeichenwechsel unter der Hauptdiagonalen und spaltentausch gemäß l beachten\nl:\n",l)


l 2 =
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
p:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
R:
 [[-8.     0.    -3.   ]
 [ 0.     4.     9.   ]
 [ 0.     0.    -3.375]]
Vorzeichenwechsel unter der Hauptdiagonalen und spaltentausch gemäß l beachten
l:
 [[ 2.     0.     0.   ]
 [ 0.625  2.     0.   ]
 [ 0.    -0.5    2.   ]]


Ly=Pb

In [14]:
l=[[5,1,3],[0,3,0],[-10,1,-3]]
ya=-28
yb=-4
yc=-27

x=ya/l[0][0]
y=(yb-l[1][0]*x)/l[1][1]
z=(yc-l[2][0]*x-l[2][1]*y)/l[2][2]
print(x,y,z)

-5.6 -1.3333333333333333 27.222222222222225


In [15]:
z=z/a[2][2]
y=(y-a[1][2]*z)/a[1][1]
x=(x-a[0][1]*y-a[0][2]*z)/a[0][0]
print(x,y,z)

-4.928888888888889 -0.4444444444444444 18.14814814814815


### mit Skalierung/Pivot.

In [13]:
import numpy as np

a=[[2,3,-3],[-3,0,-7],[4,8,6]]

def frob(a,i):
    n=len(a) #len ist die Länge von a/Dimension
    f=np.eye(n)#einheitsmatrix mit n Zeilen
    for k in range(i+1,n):#k zwischen i und n
        f[k][i]=-a[k][i]/a[i][i]
    return f

l=np.zeros((len(a),len(a)))
p=np.eye(len(a))
pi=np.eye(len(a))
temp=np.eye(len(a))
for i in range(0,len(a)-1):
    pivot=i
    p=np.eye(len(a))
    zeilensumme=np.zeros(len(a))
    for k in range(i,len(a)):
        for j in range (i,len(a)):
            zeilensumme[k]=zeilensumme[k]+abs(a[k][j])
    for k in range(i+1,len(a)):
        if abs(a[pivot][i]/zeilensumme[k-1])<abs(a[k][i]/zeilensumme[k]):
            pivot=k
    temp[0]=p[i]
    p[i]=p[pivot]
    p[pivot]=temp[0]
    a=np.dot(p,a)
    pi=np.dot(p,pi)
    l=l-(frob(a,i)-np.eye(len(a)))
    if i>0:
        print("l",i+1,"=\n",p)
    a=np.dot(frob(a,i),a)
print("p:\n",pi)
print("R:\n",a)
print("Vorzeichenwechsel unter der Hauptdiagonalen und spaltentausch gemäß l beachten\nl:\n",l)

l 2 =
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
p:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
R:
 [[-3.          0.         -7.        ]
 [ 0.          8.         -3.33333333]
 [ 0.          0.         -6.41666667]]
Vorzeichenwechsel unter der Hauptdiagonalen und spaltentausch gemäß l beachten
l:
 [[ 0.          0.          0.        ]
 [-0.66666667  0.          0.        ]
 [-1.33333333  0.375       0.        ]]


In [11]:
l=[[1,0,0],[0,1,0],[-0.8,-0.8,1]]
b=[-63,-7,-23]
import sympy as sy
y1,y2,y3=sy.symbols('y1 y2 y3')
equ=[
    sy.Eq(l[0][0]*y1,b[0]),
    sy.Eq(l[1][0]*y1+l[1][1]*y2,b[1]),
    sy.Eq(l[2][0]*y1+l[2][1]*y2+l[2][2]*y3,b[2]),
]
sy.solve(equ)

{y1: -63.0000000000000, y2: -7.00000000000000, y3: -79.0000000000000}

In [12]:
xx1,xx2,xx3=sy.symbols('xx1 xx2 xx3')
equ2=[
    sy.Eq(a[2][2]*xx1,14.4),
    sy.Eq(a[1][1]*xx1+a[1][2]*xx2,0),
    sy.Eq(a[0][0]*xx1+a[0][1]*xx2+a[0][2]*xx3,8),
    ]
sy.solve(equ2)

{xx1: 2.13333333333333, xx2: -3.79259259259259, xx3: -8.35555555555556}