In [2]:
### QR-Transformation ###

import numpy as np

maxiter=12
a=np.array([[4,-8,7,1],[8,-2,-2,2],[7,-2,24,0],[1,2,0,4]])

def qrzerlegung(a):
    q=np.eye(len(a))
    for i in range (0,len(a)-1):
        for j in range (i+1,len(a)):
            if a[j][i]!=0:
                cos=a[i][i]/np.sqrt((a[j][i])**2+(a[i][i])**2)
                sin=a[j][i]/np.sqrt((a[j][i])**2+(a[i][i])**2)
                u=np.eye(len(a))  
                u[i][i]=cos
                u[i][j]=-sin
                u[j][i]=sin
                u[j][j]=cos
                ut=np.transpose(u)
                #print("uT",i+1,j+1,"=\n",ut)
                a=np.dot(ut,a)
                q=np.dot(q,u)
                #print("q=\n",q)
                #print("a=\n",a)
    return q , a

for i in range (0,maxiter):
    q,a= qrzerlegung(a)
    a=np.dot(a,q)
    print("Iteration",i+1,"\n","a=\n",a,"\n","q=\n",q)
    #print(a*q)

Iteration 1 
 a=
 [[ 1.64705882  6.92451501  0.8660565 ]
 [-1.54867045  3.64598147 -0.81378254]
 [ 0.35229417  0.15635996 -0.29304029]] 
 q=
 [[ 0.48507125  0.38165202  0.78679579]
 [-0.48507125  0.8660565  -0.12104551]
 [-0.72760688 -0.32293632  0.60522753]]
Iteration 2 
 a=
 [[ 0.1011236   3.38053188  1.23615144]
 [-5.0085537   5.36527159  0.9689799 ]
 [-0.07271479  0.0149818  -0.46639519]] 
 q=
 [[ 0.7198443   0.68826043 -0.09012088]
 [-0.67684382  0.72476977  0.12880689]
 [ 0.15396958 -0.03172315  0.98756621]]
Iteration 3 
 a=
 [[ 5.40868397  4.91664187 -0.77146082]
 [-3.50595943  0.04889519  1.21407892]
 [ 0.00664288  0.0081179  -0.45757916]] 
 q=
 [[ 0.02018394  0.99963374  0.01802749]
 [-0.99969093  0.02044028 -0.01415033]
 [-0.01451363 -0.01773631  0.99973735]]
Iteration 4 
 a=
 [[ 3.17770140e+00  6.94375811e+00 -1.32143548e+00]
 [-1.47634661e+00  2.27938765e+00  5.96747043e-01]
 [-4.71080544e-04 -6.55383936e-04 -4.57089048e-01]] 
 q=
 [[ 8.39129107e-01  5.43929809e-01 -1.64471

In [11]:
### QR-Zerlegung ###

import numpy as np

A=np.array([[2,-2,-3],[4,1,-5],[-2,1,2]])
#B=np.array([[14.23188406,1,1,1],[1,-2.225637961781,1,1],[1,1,11.55099424,1],[1,1,1,2.44275967]]) #idk was das hier soll

for i in range(0,len(A)-1):
    for j in range (i+1,len(A)):
        if A[j][i]!=0:
            cos=A[i][i]/np.sqrt((A[j][i])**2+(A[i][i])**2)
            sin=A[j][i]/np.sqrt((A[j][i])**2+(A[i][i])**2)
            u=np.eye(len(A))  
            u[i][i]=cos
            u[i][j]=-sin
            u[j][i]=sin
            u[j][j]=cos
            ut=np.transpose(u)
            print("\nuT %d%d \n %s"% (i+1,j+1,u))
            A=np.dot(ut,A)
            print("A=\n",A)



uT 12 
 [[ 0.4472136  -0.89442719  0.        ]
 [ 0.89442719  0.4472136   0.        ]
 [ 0.          0.          1.        ]]
A=
 [[ 4.47213595  0.         -5.81377674]
 [ 0.          2.23606798  0.4472136 ]
 [-2.          1.          2.        ]]

uT 13 
 [[ 0.91287093  0.          0.40824829]
 [ 0.          1.          0.        ]
 [-0.40824829  0.          0.91287093]]
A=
 [[ 4.89897949 -0.40824829 -6.12372436]
 [ 0.          2.23606798  0.4472136 ]
 [ 0.          0.91287093 -0.54772256]]

uT 23 
 [[ 1.          0.          0.        ]
 [ 0.          0.9258201  -0.37796447]
 [ 0.          0.37796447  0.9258201 ]]
A=
 [[ 4.89897949e+00 -4.08248290e-01 -6.12372436e+00]
 [ 0.00000000e+00  2.41522946e+00  2.07019668e-01]
 [ 0.00000000e+00  5.87376257e-18 -6.76123404e-01]]
