In [18]:
### QR-Transformation ###

import numpy as np

maxiter=12
a=np.array([[4,-8,7,1],[8,-2,-2,2],[7,-2,24,0],[1,2,0,4]])

def qrzerlegung(a):
    q=np.eye(len(a))
    for i in range (0,len(a)-1):
        for j in range (i+1,len(a)):
            if a[j][i]!=0:
                cos=a[i][i]/np.sqrt((a[j][i])**2+(a[i][i])**2)
                sin=a[j][i]/np.sqrt((a[j][i])**2+(a[i][i])**2)
                u=np.eye(len(a))  
                u[i][i]=cos
                u[i][j]=-sin
                u[j][i]=sin
                u[j][j]=cos
                ut=np.transpose(u)
                #print("uT",i+1,j+1,"=\n",ut)
                a=np.dot(ut,a)
                q=np.dot(q,u)
                #print("q=\n",q)
                #print("a=\n",a)
    return q , a

for i in range (0,maxiter):
    q,a= qrzerlegung(a)
    a=np.dot(a,q)
    print("Iteration",i+1,"\n","a=\n",a,"\n","q=\n",q)
    #print(a*q)

Iteration 1 
 a=
 [[10.18461538 -7.83534239 14.96580257  4.71801004]
 [ 3.47115763  1.62175404 -6.37123611 -0.0351333 ]
 [11.74463389  2.91550014 14.77762526 -3.32957865]
 [ 0.32192187  1.29993202 -0.09915007  3.41600532]] 
 q=
 [[ 0.35082321 -0.8853979  -0.03590736  0.30282716]
 [ 0.70164642  0.24348442 -0.64567369 -0.17751937]
 [ 0.61394061  0.17707958  0.76229027 -0.10311787]
 [ 0.0877058   0.35415916 -0.02701288  0.93067142]]
Iteration 2 
 a=
 [[23.71584434 -1.65144664  7.67074614  0.21927443]
 [-1.63915759 -1.24883147 -9.39375605 -4.5227074 ]
 [ 7.29990507  5.50121967  3.28776902 -2.46969969]
 [ 0.0870012   0.70457792  0.11100104  4.24521811]] 
 q=
 [[ 0.63927197 -0.75756996 -0.06589341  0.11435546]
 [ 0.217879    0.26207316 -0.93984012 -0.02338713]
 [ 0.73719183  0.57500144  0.33420649 -0.11927942]
 [ 0.02020652  0.16364219  0.02578062  0.98597581]]
Iteration 3 
 a=
 [[ 2.63194570e+01  7.28442417e-01 -2.06123731e+00 -4.44580633e-01]
 [ 4.06161067e-01  1.16754034e+00 -6.34146223e+

In [19]:
### QR-Zerlegung ###

import numpy as np

A=np.array([[3,-3,-6],[5,1,-2],[-2,2,3]])
B=np.array([[14.23188406,1,1,1],[1,-2.225637961781,1,1],[1,1,11.55099424,1],[1,1,1,2.44275967]])

for i in range(0,len(A)-1):
    for j in range (i+1,len(A)):
        if A[j][i]!=0:
            cos=A[i][i]/np.sqrt((A[j][i])**2+(A[i][i])**2)
            sin=A[j][i]/np.sqrt((A[j][i])**2+(A[i][i])**2)
            u=np.eye(len(A))  
            u[i][i]=cos
            u[i][j]=-sin
            u[j][i]=sin
            u[j][j]=cos
            ut=np.transpose(u)
            print("\nuT %d%d \n %s"% (i+1,j+1,ut))
            A=np.dot(ut,A)
            print("A=\n",A)



uT 12 
 [[ 0.4472136   0.89442719  0.          0.        ]
 [-0.89442719  0.4472136   0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
A=
 [[ 8.94427191 -5.36656315  1.34164079  2.23606798]
 [ 0.          6.26099034 -7.15541753  0.        ]
 [ 7.         -2.         24.          0.        ]
 [ 1.          2.          0.          4.        ]]

uT 13 
 [[ 0.78749923  0.          0.61631563  0.        ]
 [ 0.          1.          0.          0.        ]
 [-0.61631563  0.          0.78749923  0.        ]
 [ 0.          0.          0.          1.        ]]
A=
 [[ 1.13578167e+01 -5.45879562e+00  1.58481163e+01  1.76090181e+00]
 [ 0.00000000e+00  6.26099034e+00 -7.15541753e+00  0.00000000e+00]
 [-8.88178420e-16  1.73249831e+00  1.80731074e+01 -1.37812365e+00]
 [ 1.00000000e+00  2.00000000e+00  0.00000000e+00  4.00000000e+00]]

uT 14 
 [[ 0.99614642  0.          0.          0.0877058 ]
 [ 0.          1.          0. 