In [24]:
### QR-Transformation ### 


import numpy as np

maxiter=12
a=np.array([[8,-3,4,1],[-3,-2,-2,8],[4,-2,24,-1],[1,8,-1,2]])

def qrzerlegung(a):
    q=np.eye(len(a))
    for i in range (0,len(a)-1):
        for j in range (i+1,len(a)):
            if a[j][i]!=0:
                cos=a[i][i]/np.sqrt((a[j][i])**2+(a[i][i])**2)
                sin=a[j][i]/np.sqrt((a[j][i])**2+(a[i][i])**2)
                u=np.eye(len(a))  
                u[i][i]=cos
                u[i][j]=-sin
                u[j][i]=sin
                u[j][j]=cos
                ut=np.transpose(u)
                #print("uT",i+1,j+1,"=\n",ut)
                a=np.dot(ut,a)
                q=np.dot(q,u)
                #print("q=\n",q)
                #print("a=\n",a)
    return q , a

for i in range (0,maxiter):
    q,a= qrzerlegung(a)
    a=np.dot(a,q)
    print("Iteration",i+1,"\n","a=\n",a,"\n","q=\n",q)
    if(i==0):
        eigenwerte = np.linalg.eigvals(a) #numpy bekommt das iwie durcheinander, so  zumindest für Beleg passend :/
        print("Eigenwerte: ",eigenwerte[1],eigenwerte[2],eigenwerte[3],eigenwerte[0])
    #print(a*q)

Iteration 1 
 a=
 [[14.31111111 -4.6296204   8.17152437 -0.85401856]
 [-4.6296204  -2.50749354 -3.31654897 -7.55147758]
 [ 8.17152437 -3.31654897 17.45615751 -0.61506064]
 [-0.85401856 -7.55147758 -0.61506064  2.74022491]] 
 q=
 [[ 0.84327404 -0.15913201 -0.4346135  -0.27327092]
 [-0.31622777 -0.29553088  0.06019047 -0.89946573]
 [ 0.42163702 -0.13639887  0.89539102 -0.04350277]
 [ 0.10540926  0.93205893  0.07591531 -0.33821872]]
Eigenwerte:  -8.779840688249255 7.167481846459975 8.301878508561366 25.310480333227886
Iteration 2 
 a=
 [[23.1162386  -3.07096129  5.31301126  0.39709356]
 [-3.07096129 -4.33118383 -0.94775106  7.08245857]
 [ 5.31301126 -0.94775106  9.66281512  0.75520915]
 [ 0.39709356  7.08245857  0.75520915  3.55213011]] 
 q=
 [[ 0.83500394 -0.10992695 -0.48784221  0.22955277]
 [-0.27012237 -0.42252925  0.03953464  0.86425687]
 [ 0.47678024 -0.13975016  0.86687151  0.04103991]
 [-0.04982904 -0.88873786 -0.09476694 -0.44573681]]
Iteration 3 
 a=
 [[25.07978035 -1.0463362   

In [12]:
### QR-Zerlegung ###

import numpy as np

A=np.array([[6,-3,-6],[5,1,-6],[-2,2,3]])
B=np.array([[14.23188406,1,1,1],[1,-2.225637961781,1,1],[1,1,11.55099424,1],[1,1,1,2.44275967]]) #idk was das hier soll

for i in range(0,len(A)-1):
    for j in range (i+1,len(A)):
        if A[j][i]!=0:
            cos=A[i][i]/np.sqrt((A[j][i])**2+(A[i][i])**2)
            sin=A[j][i]/np.sqrt((A[j][i])**2+(A[i][i])**2)
            u=np.eye(len(A))  
            u[i][i]=cos
            u[i][j]=-sin
            u[j][i]=sin
            u[j][j]=cos
            ut=np.transpose(u)
            print("\nuT %d%d \n %s"% (i+1,j+1,u))
            A=np.dot(ut,A)
            print("A=\n",A)



uT 12 
 [[ 0.76822128 -0.6401844   0.        ]
 [ 0.6401844   0.76822128  0.        ]
 [ 0.          0.          1.        ]]
A=
 [[ 7.81024968e+00 -1.66447944e+00 -8.45043408e+00]
 [-5.55111512e-16  2.68877448e+00 -7.68221280e-01]
 [-2.00000000e+00  2.00000000e+00  3.00000000e+00]]

uT 13 
 [[ 0.96874225  0.          0.24806947]
 [ 0.          1.          0.        ]
 [-0.24806947  0.          0.96874225]]
A=
 [[ 8.06225775e+00 -2.10859049e+00 -8.93050089e+00]
 [-5.55111512e-16  2.68877448e+00 -7.68221280e-01]
 [ 2.22044605e-16  1.52457796e+00  8.09932041e-01]]

uT 23 
 [[ 1.          0.          0.        ]
 [ 0.          0.86989184 -0.49324253]
 [ 0.          0.49324253  0.86989184]]
A=
 [[ 8.06225775e+00 -2.10859049e+00 -8.93050089e+00]
 [-3.73365131e-16  3.09092966e+00 -2.68776492e-01]
 [ 4.66959395e-16  1.21704080e-16  1.08347268e+00]]
